/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3.p01.Panels.Pelicula;

import m3.p01.Genero;
import m3.p01.MainFrame;
import m3.p01.Pelicula;

/**
 *
 * @author albertmarnun
 */
public class CrearPelicula extends javax.swing.JPanel {

    /**
     * Creates new form CrearPelicula
     */
    public CrearPelicula() {
        initComponents();
        cargarGeneros();
    }

    public void cargarGeneros(){
        crearPeliculaGeneroCombo.addItem(Genero.ACCION);
        crearPeliculaGeneroCombo.addItem(Genero.CIENCIA_FICCION);
        crearPeliculaGeneroCombo.addItem(Genero.COMEDIA);
        crearPeliculaGeneroCombo.addItem(Genero.TERROR);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crearPeliculaTituloTxt = new javax.swing.JTextField();
        crearPeliculaDirectorTxt = new javax.swing.JTextField();
        crearPeliculaAnyoTxt = new javax.swing.JTextField();
        crearPeliculaDuracionTxt = new javax.swing.JTextField();
        crearPeliculaGeneroCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        crearPeliculaSinopsisTxtArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 279));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Titulo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("Director");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("Año");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel4.setText("Genero");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jLabel5.setText("Duración");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        jLabel6.setText("Sinopsis");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));
        add(crearPeliculaTituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 11, 260, -1));
        add(crearPeliculaDirectorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 37, 260, -1));
        add(crearPeliculaAnyoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 63, 70, -1));
        add(crearPeliculaDuracionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 115, 70, -1));

        add(crearPeliculaGeneroCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 89, 70, -1));

        crearPeliculaSinopsisTxtArea.setColumns(20);
        crearPeliculaSinopsisTxtArea.setRows(5);
        jScrollPane1.setViewportView(crearPeliculaSinopsisTxtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 260, -1));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            MainFrame.cines.get(0).addPelicula(new Pelicula(crearPeliculaTituloTxt.getText(), 
                    crearPeliculaDirectorTxt.getText(), Integer.parseInt(crearPeliculaAnyoTxt.getText()), 
                    crearPeliculaSinopsisTxtArea.getText(), 
                    (Genero)crearPeliculaGeneroCombo.getSelectedItem(),
                    Integer.parseInt(crearPeliculaDuracionTxt.getText())));
            MainFrame.infoCorrect("Se ha creado correctamente.");
        }catch(Exception e){
            MainFrame.infoFail("No se ha creado la pelicula.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crearPeliculaAnyoTxt;
    private javax.swing.JTextField crearPeliculaDirectorTxt;
    private javax.swing.JTextField crearPeliculaDuracionTxt;
    private javax.swing.JComboBox crearPeliculaGeneroCombo;
    private javax.swing.JTextArea crearPeliculaSinopsisTxtArea;
    private javax.swing.JTextField crearPeliculaTituloTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
