/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3.p01.Panels.Pelicula;

import javax.swing.table.DefaultTableModel;
import m3.p01.MainFrame;

/**
 *
 * @author albertribgar
 */
public class MostrarCartelera extends javax.swing.JPanel {

    /**
     * Creates new form MostrarCartelera
     */
    public MostrarCartelera() {
        initComponents();
        cargarPeliculas();
    }

    private void cargarPeliculas(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i = 0; i<MainFrame.cines.get(0).getPelicula().size(); i++){
            String titulo = MainFrame.cines.get(0).getPelicula().get(i).getTitulo();
            String autor = MainFrame.cines.get(0).getPelicula().get(i).getDirector();
            String genero = MainFrame.cines.get(0).getPelicula().get(i).getGenero().toString();
            String duracion = String.valueOf(MainFrame.cines.get(0).getPelicula().get(i).getDuracion());
            String fecha = String.valueOf(MainFrame.cines.get(0).getPelicula().get(i).getAnyo());
            String comentario = MainFrame.cines.get(0).getPelicula().get(i).getSinopsis();
            model.addRow(new String[]{titulo, autor, duracion, genero, fecha,comentario});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Director", "Duracion", "Genero", "Fecha", "Comentario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
