/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3.p01.Panels.Sesion;

/**
 *
 * @author albertribgar
 */
public class ConsultarSesiones extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarSesiones
     */
    private boolean fechacond;
    public ConsultarSesiones() {
        initComponents();
        inicio();
    }
    
    private void inicio(){
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        ConsultarSesionesTxtDia.setVisible(false);
        ConsultarSesionesTxtMes.setVisible(false);
        ConsultarSesionesTxtAño.setVisible(false);
        jLabel2.setVisible(false);
        ConsultarSesionesTxtSala.setVisible(false);
        ConsultarSesionesBtBuscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ConsultarSesionesTxtSala = new javax.swing.JTextField();
        ConsultarSesionesRadioDia = new javax.swing.JRadioButton();
        ConsultarSesionesRadioSala = new javax.swing.JRadioButton();
        ConsultarSesionesTxtDia = new javax.swing.JTextField();
        ConsultarSesionesTxtMes = new javax.swing.JTextField();
        ConsultarSesionesTxtAño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        ConsultarSesionesBtBuscar = new javax.swing.JButton();

        jLabel1.setText("Número de sala");

        jLabel2.setText("Día de la sesión");

        ConsultarSesionesRadioDia.setText("Día");
        ConsultarSesionesRadioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSesionesRadioDiaActionPerformed(evt);
            }
        });

        ConsultarSesionesRadioSala.setText("Sala");
        ConsultarSesionesRadioSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSesionesRadioSalaActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        jLabel4.setText("/");

        jScrollPane1.setViewportView(jList1);

        ConsultarSesionesBtBuscar.setText("Buscar");
        ConsultarSesionesBtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSesionesBtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ConsultarSesionesTxtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ConsultarSesionesTxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultarSesionesTxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultarSesionesTxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConsultarSesionesBtBuscar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ConsultarSesionesRadioDia)
                        .addGap(33, 33, 33)
                        .addComponent(ConsultarSesionesRadioSala)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarSesionesRadioDia)
                    .addComponent(ConsultarSesionesRadioSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ConsultarSesionesTxtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultarSesionesTxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultarSesionesTxtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarSesionesTxtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConsultarSesionesBtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarSesionesRadioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSesionesRadioDiaActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        ConsultarSesionesTxtDia.setVisible(true);
        ConsultarSesionesTxtMes.setVisible(true);
        ConsultarSesionesTxtAño.setVisible(true);
        jLabel2.setVisible(false);
        ConsultarSesionesTxtSala.setVisible(false);
        fechacond=true;
        ConsultarSesionesBtBuscar.setVisible(true);
    }//GEN-LAST:event_ConsultarSesionesRadioDiaActionPerformed

    private void ConsultarSesionesRadioSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSesionesRadioSalaActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        ConsultarSesionesTxtDia.setVisible(false);
        ConsultarSesionesTxtMes.setVisible(false);
        ConsultarSesionesTxtAño.setVisible(false);
        jLabel2.setVisible(true);
        ConsultarSesionesTxtSala.setVisible(true);
        fechacond=false;
        ConsultarSesionesBtBuscar.setVisible(true);
    }//GEN-LAST:event_ConsultarSesionesRadioSalaActionPerformed

    private void ConsultarSesionesBtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSesionesBtBuscarActionPerformed
        // TODO add your handling code here:
        if (fechacond){
            
        }else{
            
        }
    }//GEN-LAST:event_ConsultarSesionesBtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarSesionesBtBuscar;
    private javax.swing.JRadioButton ConsultarSesionesRadioDia;
    private javax.swing.JRadioButton ConsultarSesionesRadioSala;
    private javax.swing.JTextField ConsultarSesionesTxtAño;
    private javax.swing.JTextField ConsultarSesionesTxtDia;
    private javax.swing.JTextField ConsultarSesionesTxtMes;
    private javax.swing.JTextField ConsultarSesionesTxtSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
