/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3.p01.Panels.Sesion;

import java.util.Calendar;
import m3.p01.MainFrame;
import m3.p01.Sesion;

/**
 *
 * @author albertmarnun
 */
public class CrearSesion extends javax.swing.JPanel {

    /**
     * Creates new form CrearSesion
     */
    public CrearSesion() {
        initComponents();
        cargarSalas();
        cargarPeliculas();
    }
    private void cargarSalas(){
        for (int i = 0; i<MainFrame.salas.size(); i++){
            crearSesionSalaCombo.addItem((i+1)+" - Sala: "+MainFrame.salas.get(i).getNumSala());
        }
    }
    private void cargarPeliculas(){
        for (int i = 0; i<MainFrame.peliculas.size(); i++){
            crearSesionPeliculaCombo.addItem((i+1)+" - "+MainFrame.peliculas.get(i).getTitulo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crearSesionSalaCombo = new javax.swing.JComboBox();
        crearSesionPeliculaCombo = new javax.swing.JComboBox();
        crearSesionButacasVendidasTxt = new javax.swing.JTextField();
        crearSesionFechaDiaTxt = new javax.swing.JTextField();
        crearSesionFechaMesTxt = new javax.swing.JTextField();
        crearSesionFechaAnyoTxt = new javax.swing.JTextField();
        crearSesionFechaHoraTxt = new javax.swing.JTextField();
        crearSesionFechaMinTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        crearSesionCrearBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 279));

        jLabel1.setText("Sala");

        jLabel2.setText("Pelicula");

        jLabel3.setText("Butacas Vendidas");

        jLabel4.setText("Fecha");

        crearSesionFechaDiaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        crearSesionFechaMesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crearSesionFechaMesTxt.setPreferredSize(new java.awt.Dimension(15, 20));

        crearSesionFechaAnyoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crearSesionFechaAnyoTxt.setPreferredSize(new java.awt.Dimension(15, 20));

        crearSesionFechaHoraTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crearSesionFechaHoraTxt.setPreferredSize(new java.awt.Dimension(15, 20));

        crearSesionFechaMinTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        crearSesionFechaMinTxt.setPreferredSize(new java.awt.Dimension(15, 20));

        jLabel5.setText("Dia");

        jLabel6.setText("Mes");

        jLabel7.setText("Año");

        jLabel8.setText("Hora");

        jLabel9.setText("Min");

        crearSesionCrearBtn.setText("Crear");
        crearSesionCrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSesionCrearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(crearSesionFechaDiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(crearSesionFechaMesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(crearSesionFechaAnyoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(crearSesionFechaHoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(crearSesionFechaMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crearSesionButacasVendidasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(crearSesionPeliculaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearSesionSalaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(crearSesionCrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {crearSesionFechaAnyoTxt, crearSesionFechaDiaTxt, crearSesionFechaHoraTxt, crearSesionFechaMesTxt, crearSesionFechaMinTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(crearSesionSalaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(crearSesionPeliculaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(crearSesionButacasVendidasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(crearSesionFechaDiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(1, 1, 1)
                            .addComponent(crearSesionFechaMesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(1, 1, 1)
                            .addComponent(crearSesionFechaAnyoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(1, 1, 1)
                            .addComponent(crearSesionFechaHoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(1, 1, 1)
                        .addComponent(crearSesionFechaMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(crearSesionCrearBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {crearSesionFechaAnyoTxt, crearSesionFechaDiaTxt, crearSesionFechaHoraTxt, crearSesionFechaMesTxt, crearSesionFechaMinTxt});

    }// </editor-fold>//GEN-END:initComponents

    private void crearSesionCrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSesionCrearBtnActionPerformed
        // TODO add your handling code here:
        int nsala = crearSesionSalaCombo.getSelectedIndex();
        int npelicula = crearSesionPeliculaCombo.getSelectedIndex();
        int nvendidas = Integer.parseInt(crearSesionButacasVendidasTxt.getText());
        int dia = Integer.parseInt(crearSesionFechaDiaTxt.getText());
        int mes = Integer.parseInt(crearSesionFechaMesTxt.getText());
        int año = Integer.parseInt(crearSesionFechaAnyoTxt.getText());
        int hora = Integer.parseInt(crearSesionFechaHoraTxt.getText());
        int min = Integer.parseInt(crearSesionFechaMinTxt.getText());
        Sesion sesion = new Sesion(MainFrame.peliculas.get(npelicula), MainFrame.salas.get(nsala), año, mes, dia, hora, min);
        sesion.actualizarButacasVendidas(nvendidas);
        MainFrame.sesiones.add(sesion);
    }//GEN-LAST:event_crearSesionCrearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crearSesionButacasVendidasTxt;
    private javax.swing.JButton crearSesionCrearBtn;
    private javax.swing.JTextField crearSesionFechaAnyoTxt;
    private javax.swing.JTextField crearSesionFechaDiaTxt;
    private javax.swing.JTextField crearSesionFechaHoraTxt;
    private javax.swing.JTextField crearSesionFechaMesTxt;
    private javax.swing.JTextField crearSesionFechaMinTxt;
    private javax.swing.JComboBox crearSesionPeliculaCombo;
    private javax.swing.JComboBox crearSesionSalaCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
