/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m3.p01.Panels.Sala;

import m3.p01.MainFrame;

/**
 *
 * @author albertmarnun
 */
public class ModificarSala extends javax.swing.JPanel {

    /**
     * Creates new form CrearSala
     */
    int indice;
    public ModificarSala(int index) {
        initComponents();
        indice = index;
        modificarSalaNumeroSalaTxt.setText(String.valueOf(MainFrame.salas.get(indice).getNumSala()));
        modificarSalaNumeroButacasTxt.setText(String.valueOf(MainFrame.salas.get(indice).getNButacas()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modificarSalaNumeroButacasTxt = new javax.swing.JTextField();
        modificarSalaNumeroSalaTxt = new javax.swing.JTextField();
        modificarSalaCrearBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 279));

        jLabel1.setText("Nº de Sala ");

        jLabel2.setText("Nº de Butacas");

        modificarSalaNumeroSalaTxt.setEnabled(false);

        modificarSalaCrearBtn.setText("Crear");
        modificarSalaCrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarSalaCrearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modificarSalaCrearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(modificarSalaNumeroButacasTxt)
                            .addComponent(modificarSalaNumeroSalaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarSalaNumeroSalaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarSalaNumeroButacasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(modificarSalaCrearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarSalaCrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarSalaCrearBtnActionPerformed
        // TODO add your handling code here:
        MainFrame.salas.get(indice).setNButacas(Integer.parseInt(modificarSalaNumeroButacasTxt.getText()));
    }//GEN-LAST:event_modificarSalaCrearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificarSalaCrearBtn;
    private javax.swing.JTextField modificarSalaNumeroButacasTxt;
    private javax.swing.JTextField modificarSalaNumeroSalaTxt;
    // End of variables declaration//GEN-END:variables
}
